import geoData from '../data/city-geo.json';

// Projection constants live in mapProjection.ts (dependency-free, safe to
// bundle into client JS); re-exported here for existing importers.
export {
  MAP_LON0,
  MAP_LON1,
  MAP_LAT0,
  MAP_LAT1,
  MAP_W,
  MAP_H,
  projectX,
  projectY,
  unprojectX,
  unprojectY,
} from './mapProjection';

// --- City geocoding lookup (generated by pipeline/.scratch/build_city_geo.py)
export interface CityGeo {
  lon: number;
  lat: number;
  /** State/province display name, null when unknown. */
  state: string | null;
  /** False when only the country-capital fallback matched. */
  exact: boolean;
}

const data = geoData as {
  countries: Record<string, { lon: number; lat: number }>;
  cities: Record<string, { lon: number; lat: number; state: string }>;
};

export function lookupCity(country: string, city: string): CityGeo | null {
  const hit = data.cities[`${country}||${city}`];
  if (hit) return { lon: hit.lon, lat: hit.lat, state: hit.state || null, exact: true };
  const fallback = data.countries[country];
  if (!fallback) return null;
  return { lon: fallback.lon, lat: fallback.lat, state: null, exact: false };
}
