import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

/**
 * Weekly/monthly reports generated by pipeline/report.py into
 * ../data/reports/{weekly,monthly}-<period>.json.
 */

const ReportThemeSchema = z.object({
  heading: z.string(),
  narrative: z.string(),
  story_ids: z.array(z.string()).min(1),
});

const MilestoneSchema = z.object({
  project_id: z.string(),
  name: z.string(),
  operator: z.string(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  change: z.string(),
  kind: z.enum(['first_tracked', 'status_change']).optional(),
  // news = from a tracked story; directory_sync = from the weekly
  // DataCenterMap re-scan (rendered with a "via directory refresh" note).
  origin: z.enum(['news', 'directory_sync']).optional(),
  status: z.string().optional(),
  prev_status: z.string().nullable().optional(),
  // Absent/null on directory_sync milestones (no linked story).
  story_id: z.string().nullish(),
});

const ReportSchema = z.object({
  type: z.enum(['weekly', 'monthly']),
  period: z.string(),
  date_range: z.object({
    start: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    end: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  }),
  generated_at: z.string(),
  // false = period still in progress or days missing from the archive.
  complete: z.boolean().default(true),
  stats: z.object({
    stories: z.number().int().nonnegative(),
    sources: z.number().int().nonnegative(),
    days: z.number().int().nonnegative(),
    read_minutes: z.number().int().positive(),
  }),
  title: z.string(),
  lede: z.string(),
  themes: z.array(ReportThemeSchema),
  project_milestones: z.array(MilestoneSchema),
});

export type Report = z.infer<typeof ReportSchema>;
export type ReportTheme = z.infer<typeof ReportThemeSchema>;
export type ReportMilestone = z.infer<typeof MilestoneSchema>;

const DATA_DIR = fileURLToPath(new URL('../../../data/reports', import.meta.url));

// Build-time memo: pages call this per getStaticPaths; files never change
// mid-build (same contract as lib/projects.ts).
let reportsCache: Report[] | null = null;

/** All reports, newest period first. */
export function loadReports(): Report[] {
  if (reportsCache) return reportsCache;
  const reports: Report[] = [];
  if (existsSync(DATA_DIR)) {
    for (const file of readdirSync(DATA_DIR)) {
      if (!file.endsWith('.json')) continue;
      try {
        const parsed = ReportSchema.safeParse(JSON.parse(readFileSync(join(DATA_DIR, file), 'utf-8')));
        if (parsed.success) reports.push(parsed.data);
        else console.warn(`[reports] skipping invalid file ${file}:`, parsed.error.issues[0]?.message);
      } catch (err) {
        console.warn(`[reports] failed to read ${file}:`, err);
      }
    }
  }
  reports.sort((a, b) => (a.date_range.end < b.date_range.end ? 1 : -1));
  reportsCache = reports;
  return reports;
}

/** Short issue badge for the rail: "W34" / "Aug". */
export function issueBadge(report: Report): string {
  if (report.type === 'weekly') {
    const m = /-W(\d{2})$/.exec(report.period);
    return m ? `W${Number(m[1])}` : report.period;
  }
  return new Date(`${report.date_range.start}T12:00:00Z`).toLocaleDateString('en-US', {
    month: 'short',
    timeZone: 'UTC',
  });
}

/** "August 17 – 23, 2026" / "August 1 – 31, 2026". */
export function formatRange(report: Report): string {
  const start = new Date(`${report.date_range.start}T12:00:00Z`);
  const end = new Date(`${report.date_range.end}T12:00:00Z`);
  const opts: Intl.DateTimeFormatOptions = { month: 'long', day: 'numeric', timeZone: 'UTC' };
  const sameMonth = start.getUTCMonth() === end.getUTCMonth() && start.getUTCFullYear() === end.getUTCFullYear();
  const s = start.toLocaleDateString('en-US', opts);
  const e = end.toLocaleDateString('en-US', { ...opts, year: 'numeric' });
  return `${s} – ${e}`;
}

/**
 * Rail grouping: reports bucketed by the month their period starts in,
 * newest month first, each bucket's issues newest first.
 */
export function groupByMonth(reports: Report[]): { label: string; key: string; reports: Report[] }[] {
  const groups = new Map<string, { label: string; reports: Report[] }>();
  for (const report of reports) {
    const d = new Date(`${report.date_range.start}T12:00:00Z`);
    const key = report.date_range.start.slice(0, 7);
    if (!groups.has(key)) {
      groups.set(key, {
        label: d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', timeZone: 'UTC' }),
        reports: [],
      });
    }
    groups.get(key)!.reports.push(report);
  }
  return [...groups.entries()]
    .sort(([a], [b]) => (a < b ? 1 : -1))
    .map(([key, g]) => ({ key, label: g.label, reports: g.reports }));
}

/** URL path (relative to BASE_URL) for a report issue. */
export function reportPath(report: Report): string {
  return `/reports/${report.type}/${report.period}/`;
}
